name: Markdown Linker
description: An actions that creates links between markdown documents based upon tags
author: DaanV2
branding:
  icon: archive
  color: purple
inputs:
  folder:
    description: The folder to start as from, default to github.workspace
    required: false
    default: ${{ github.workspace }}
  ignore:
    description: Glob patterns to use on what files / folder to ignore, each line is a pattern
    required: false
    default: ""
runs:
  using: node20
  main: dist/index.js