name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        
      - name: Update
        continue-on-error: true
        run: |
          git add .
          git commit -m "auto: Updated to ${{ github.ref }}"
          git push --tags
          git push
